### ISSUE TITLE
Add Apple Music Functionality

### ISSUE THREAD

**Issue by rileycleavenger** [rileycleavenger/TheModernJukebox#14]
Allow users to sign in with apple music within an instance, and route all of their music data in the instance

- [ ] Allow users to sign into their apple music account
- [ ] keep the user signed in within the instance
- [ ] display the user's music data on the Music Player page

**Comment by r3noble** [comment]
Problems for future development:
PLEASE NOTE THAT APPLE MUSIC API LOGIN IS NOT IMPLEMENTED YET DUE TO BELOW ISSUES.
There are many more hoops to jump through to get access to the Apple Music API through iPod JS. Our project cannot simply access the API, it has to acquire developer tokens. In order to do this, our team would have to sign up for the Apple Developer program with government IDs through an application process. Additionally, we would have to pay a yearly fee of $100 to be able to access the API using developer tokens.
On top of this, there are specific policies that Apple has in place that could get in the way of future development. In addition to waiting for our application to be approved and paying the fee, once our project has access to the API we only have a limited number of times that our token can be used in a given amount of time. This could cause many issues in development, more specifically in terms of testing and deployment of the software itself, as having a limited number of times we can connect to the API could mean that the Apple Music portion of our software could possibly be non-operational for a substantial amount of time.
All this information was gathered by looking into the Apple Music API documentation, as well as through a lengthy phone call with Apple Developer Support. Future work into this sector of the project will need consultation with Chase Ruskin as well as a consensus among the project group as to where to go next.
